### PR TITLE
Make sure that failed test cases are properly categorized.

### PR DESCRIPTION
**Pull request by omaciel**
I noticed that failed test cases from a JUNIT file were being counted as `PASSED`.
The proposed change fix that.

### CODE REVIEW

**Comment by omaciel** [comment]
Before:

``` python
In [1]: from betelgeuse import parse_junit

In [2]: from collections import Counter

In [3]: results = parse_junit("/Users/omaciel/Downloads/foreman-results.xml")

In [4]: Counter([x['status'] for x in results])
Out[4]: Counter({'passed': 381, 'skipped': 20})
```

After:

``` python
In [1]: from betelgeuse import parse_junit

In [2]: from collections import Counter

In [3]: results = parse_junit("/Users/omaciel/Downloads/foreman-results.xml")

In [4]: Counter([x['status'] for x in results])
Out[4]: Counter({'failure': 12, u'passed': 369, 'skipped': 20})
```

**Comment by omaciel** [comment]
Will rebase

**Comment by omaciel** [comment]
Rebased

**Comment by sthirugn** [comment]
ACK

**Comment by elyezer** [comment]
APT

**Pull request merged**
