### PR TITLE
Fix python 3.9 compatibility

### LINKED ISSUE #133: AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren' with Python 3.9
Hello, when running betelgeuse test-run command in python 3.9 I see below traceback:
```
Traceback (most recent call last):

  File "/usr/local/bin/betelgeuse", line 8, in <module>

    sys.exit(cli())

  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__

    return self.main(*args, **kwargs)

  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main

    rv = self.invoke(ctx)

  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke

    return callback(*args, **kwargs)

  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func

    return ctx.invoke(f, obj, *args, **kwargs)

  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke

    return callback(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/betelgeuse/__init__.py", line 789, in test_run

    testsuite = testsuite.getchildren()[0]

AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren' 
```
getchildren was deprecated and in 3.9 it was removed from python library.  Please update code.

### PR DESCRIPTION
**Pull request by lpramuk**
Fixes https://github.com/SatelliteQE/betelgeuse/issues/133

### CODE REVIEW

**Comment by lpramuk** [comment]
@elyezer Do you think we need to do another release in order to deliver fix to pypi ?

-edit: The question is more about if you would do it now or we wait to capture more fixes. In CI our team uses python3.8 I hit it when running locally on my F33

**Comment by elyezer** [comment]
@lpramuk it seems that travis is not running here and trying to run `make test` locally was giving some failures.

To you question, I think it is fine to add a new release with the compatibility to Python 3.9 so we don't need to wait for further improvements. But let's get travis working again and make sure we are really compatible with all the different versions we are supporting currently.

**Comment by lpramuk** [comment]
Ack.
@elyezer  travis stopped working in our organization some time ago. we use GH actions instead:
https://github.com/SatelliteQE/robottelo/blob/master/.github/workflows/pull_request.yml

**Comment by elyezer** [comment]
I am working on https://github.com/SatelliteQE/betelgeuse/pull/137 and it should be ready in a few.

**Comment by elyezer** [comment]
@lpramuk please rebase after https://github.com/SatelliteQE/betelgeuse/pull/137 and add the 3.9 permutation to the github workflow instead of the travis ci that is now gone.

**Review by elyezer — CHANGES_REQUESTED** [review]
Please rebase and add the 3.9 on the github action. Travis is not used anymore after #137

**Comment by lpramuk** [comment]
@elyezer Rebased. Ready to ship :-)

**Review by elyezer — APPROVED** [review]
Thanks @lpramuk for the changes

**Comment by elyezer** [comment]
@lpramuk I just released https://pypi.org/project/Betelgeuse/1.9.0/ to publish the compatibility you've added. Thank you

**Pull request merged**
